

// Could be changed by the admin at any time
export const currency = {
  'CAD_XAF': 426.07,
};

export const dummyPost = {
  id: 7,
  title: '[title] Apple pie soufflé candy',
  description: 'Chocolate cake icing pie dragée jujubes sweet roll apple pie jelly icing. Jelly-o gingerbread sweet ',
  price: '700.00',
  make: 'toyota',
  year: '2000',
  bodyType: 'sedan',
  kilometers: '200,000',
  color: 'red',
  transmission: 'automatic',
  nbDoors: '4',
  fuelType: 'Gasoline',
  date: '11/07/2018',
  isVisible: true,
};

export const user = {
  biography: '--------?mmmmm',
  displayName: 'Eric Njan?????',
  email: 'eric.njanga@gmail.com',
  lastSignin: 1531940865148,
  lat: 43.6513932,
  lng: -79.5642048,
  phoneNumber: 'xxx xxxx xxx',
  photoURL: 'https://lh5.googleusercontent.com/-COiFmnKgWAY/AAAAAAAAAAI/AAAAAAAABTk/gGWhai835yE/photo.jpg',
  uid: '0D2s9A7OyLQqZJS6sdse1SZgspK2',
  visible: true,
};


export const dummyPosts = [
  {
    key: 0,
    title: '[title] Apple pie soufflé candy',
    description: 'Chocolate cake icing pie dragée jujubes sweet roll apple pie jelly icing. Jelly-o gingerbread sweet ',
    price: '700.00',
    make: 'toyota',
    year: '2000',
    bodyType: 'sedan',
    kilometers: '200,000',
    color: 'red',
    transmission: 'automatic',
    nbDoors: '4',
    fuelType: 'Gasoline',
    date: '11/07/2018',
    isVisible: true,
  },
  {
    key: 1,
    title: '[title] Apple pie soufflé candy',
    description: 'Chocolate cake icing pie dragée jujubes sweet roll apple pie jelly icing. Jelly-o gingerbread sweet ',
    price: '700.00',
    make: 'toyota',
    year: '2000',
    bodyType: 'sedan',
    kilometers: '200,000',
    color: 'red',
    transmission: 'automatic',
    nbDoors: '4',
    fuelType: 'Gasoline',
    date: '11/07/2018',
    isVisible: true,
  },{
    key: 2,
    title: '[title] Apple pie soufflé candy',
    description: 'Chocolate cake icing pie dragée jujubes sweet roll apple pie jelly icing. Jelly-o gingerbread sweet ',
    price: '700.00',
    make: 'toyota',
    year: '2000',
    bodyType: 'sedan',
    kilometers: '200,000',
    color: 'red',
    transmission: 'automatic',
    nbDoors: '4',
    fuelType: 'Gasoline',
    date: '11/07/2018',
    isVisible: true,
  },{
    key: 3,
    title: '[title] Apple pie soufflé candy',
    description: 'Chocolate cake icing pie dragée jujubes sweet roll apple pie jelly icing. Jelly-o gingerbread sweet ',
    price: '700.00',
    make: 'toyota',
    year: '2000',
    bodyType: 'sedan',
    kilometers: '200,000',
    color: 'red',
    transmission: 'automatic',
    nbDoors: '4',
    fuelType: 'Gasoline',
    date: '11/07/2018',
    isVisible: true,
  },{
    key: 14,
    title: '[title] Apple pie soufflé candy',
    description: 'Chocolate cake icing pie dragée jujubes sweet roll apple pie jelly icing. Jelly-o gingerbread sweet ',
    price: '700.00',
    make: 'toyota',
    year: '2000',
    bodyType: 'sedan',
    kilometers: '200,000',
    color: 'red',
    transmission: 'automatic',
    nbDoors: '4',
    fuelType: 'Gasoline',
    date: '11/07/2018',
    isVisible: true,
  },{
    key: 4,
    title: '[title] Apple pie soufflé candy',
    description: 'Chocolate cake icing pie dragée jujubes sweet roll apple pie jelly icing. Jelly-o gingerbread sweet ',
    price: '700.00',
    make: 'toyota',
    year: '2000',
    bodyType: 'sedan',
    kilometers: '200,000',
    color: 'red',
    transmission: 'automatic',
    nbDoors: '4',
    fuelType: 'Gasoline',
    date: '11/07/2018',
    isVisible: true,
  },{
    key: 5,
    title: '[title] Apple pie soufflé candy',
    description: 'Chocolate cake icing pie dragée jujubes sweet roll apple pie jelly icing. Jelly-o gingerbread sweet ',
    price: '700.00',
    make: 'toyota',
    year: '2000',
    bodyType: 'sedan',
    kilometers: '200,000',
    color: 'red',
    transmission: 'automatic',
    nbDoors: '4',
    fuelType: 'Gasoline',
    date: '11/07/2018',
    isVisible: true,
  },{
    key: 6,
    title: '[title] Apple pie soufflé candy',
    description: 'Chocolate cake icing pie dragée jujubes sweet roll apple pie jelly icing. Jelly-o gingerbread sweet ',
    price: '700.00',
    make: 'toyota',
    year: '2000',
    bodyType: 'sedan',
    kilometers: '200,000',
    color: 'red',
    transmission: 'automatic',
    nbDoors: '4',
    fuelType: 'Gasoline',
    date: '11/07/2018',
    isVisible: true,
  },{
    key: 7,
    title: '[title] Apple pie soufflé candy',
    description: 'Chocolate cake icing pie dragée jujubes sweet roll apple pie jelly icing. Jelly-o gingerbread sweet ',
    price: '700.00',
    make: 'toyota',
    year: '2000',
    bodyType: 'sedan',
    kilometers: '200,000',
    color: 'red',
    transmission: 'automatic',
    nbDoors: '4',
    fuelType: 'Gasoline',
    date: '11/07/2018',
    isVisible: true,
  }
];


export const appText = {
  loginIntro: `<b>[login - introText]</b> Chocolate bar apple pie lollipop brownie carrot 
  cake halvah chocolate bar. Toffee candy tiramisu gummi bears. Halvah 
  cake cheesecake.`,
  about: ``,
};

export const adminDefault = {
  id: '-LIkl4k0oAv47lZc1GqQ',
  // name: "admin",  --- online
  // password: "11"
};
